export const TypeMultiple = require('./Multiple')
export const TypeAdmin = require('./Admin')
export const TypeInterval = require('./Interval')
export const TypeInput = require('./Input')
export const TypeSort = require('./Sort')
export const TypeSelect = require('./Select')